title: Museum Techniques in the 21st Century
subtitle: Advanced Course · BIODIV Doctoral Programme
description: website course
repository:
url:
baseurl: "/biodiv_museum_course"
remote_theme: mmistakes/minimal-mistakes@4.27.0
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
minimal_mistakes_skin: default

atom_feed:
  hide: true
  
footer:
  text: "© 2025 · all rights reserved ·"
  links:
    - label: Ricardo Jorge Lopes Lab
      icon: "fas fa-link"
      url: "https://ricardojorgelopes.com"